services:
  # run interactive with:
  #   docker compose run --rm supabase sh
  supabase:
    build:
      context: .
      # node:26-bookworm-slim has this error. 25 did not.:
      #    (node:9) [DEP0205] DeprecationWarning: `module.register()` is deprecated. Use `module.registerHooks()` instead.
      dockerfile_inline: |
        FROM node:25-bookworm-slim
        RUN --mount=type=cache,target=/root/.npm npm install -g @supabase/lite postgres
        WORKDIR /app
    working_dir: "/app"
    user: "1000:1000"
    # lite init may be necessary
    command: sh -c "lite dev --config /app/supabase/lite-config.toml --admin"
      #command: sh -c "lite dev --config /app/supabase/lite-config.toml --host --admin"
      #    ports:
      #      - "54321:54321"
      #      - "54323:54323"
    network_mode: host
    volumes:
      - .:/app/
      # Use lite db diff to create migrations
  squatbags:
    build:
      context: .
      dockerfile_inline: |
        FROM node:25-bookworm-slim
        RUN --mount=type=cache,target=/root/.npm npm install -g quasar @quasar/app-vite
        WORKDIR /app
    working_dir: "/app"
    user: "1000:1000"
    # lite init may be necessary
    command: sh -c "npm run dev"
      #command: sh -c "lite dev --config /app/supabase/lite-config.toml --host --admin"
    ports:
      - "9000:9000"
    # network_mode: host
    volumes:
      - ./squatbags:/app/
      # Use lite db diff to create migrations
   
