services:
  #   pgmain:
  #     environment: &psqlenv
  #       POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
  #       PGDATA: /data/postgres
  #     hostname: pgmain
  #     image: postgres:17-bookworm
  #     # container_name: pgmain_container
  #     # image: pgmain_image
  #     # build:
  #     #   context: "${COMPOSE_DIR:-.}"
  #     #   dockerfile: pgmain.dockerfile
  #     #   args:
  #     #     DB_NAME: pgmain
  #     # volumes:
  #     #    - pgmain_vol:/data/postgres
  #     #    - "${COMPOSE_DIR:-.}/mnt/pgmain:/mnt/pgmain:rw"
  #     #    - "${COMPOSE_DIR:-.}/mnt/shared:/mnt/shared:rw"
  #     ports:
  #       - "5431:5432"
  #     networks:
  #       - postgres
  #     restart: unless-stopped
  #     # deploy:
  #     #   resources:
  #     #     limits:
  #     #       memory: 100M
  # run interactive with:
  #   docker compose run --rm supabase sh
  supabase:
    build:
      context: .
      # node:26-bookworm-slim has this error. 25 did not.:
      #    (node:9) [DEP0205] DeprecationWarning: `module.register()` is deprecated. Use `module.registerHooks()` instead.
      dockerfile_inline: |
        FROM node:25-bookworm-slim
        RUN --mount=type=cache,target=/root/.npm npm install -g @supabase/lite postgres
        WORKDIR /app
    working_dir: "/app"
    user: "1000:1000"
    # lite init may be necessary
    #command: sh -c "lite dev --config /app/supabase/lite-config.toml --host --admin"
    command: sh -c "lite dev --config /app/supabase/lite-config.toml --admin --host"
      #command: sh -c "lite dev --config /app/supabase/lite-config.toml --host --admin"
      #    ports:
      #      - "54321:54321"
      #      - "54323:54323"
    network_mode: host
    volumes:
      - .:/app/
      # Use lite db diff to create migrations
    # depends_on:
    #   - pgmain
  squatbags:
    build:
      context: .
      dockerfile_inline: |
        FROM node:25-bookworm-slim
        RUN --mount=type=cache,target=/root/.npm npm install -g quasar @quasar/app-vite
        WORKDIR /app
    working_dir: "/app"
    user: "1000:1000"
    # lite init may be necessary
    command: sh -c "npm run dev"
    ports:
      - "9000:9000"
    # network_mode: host
    volumes:
      - ./squatbags:/app/
      # Use lite db diff to create migrations
   
networks:
  postgres:
    driver: bridge
