version: "3"
services:
  # run interactive with:
  #   docker compose run --rm supabase sh
  supabase:
    build:
      context: .
      dockerfile_inline: |
        FROM node:26-bookworm-slim
        RUN --mount=type=cache,target=/root/.npm npm install -g @supabase/lite
        WORKDIR /app
    working_dir: "/app"
    user: "1000:1000"
    command: lite init --pglite; lite dev --config /app/lite-config.toml
    ports:
      - "54321:54321"
    volumes:
      - .:/app/
      # Use lite db diff to create migrations

