-- Create an enum type for your permission levels
create type app_role as enum ('admin', 'moderator', 'user');

-- Create a table to link profiles to a specific role
create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  role app_role not null default 'user',
  unique (user_id)
);

-- https://makerkit.dev/docs/next-supabase-turbo/development/permissions-and-roles
create function public.authorize(requested_role app_role)
returns boolean as $$
declare
  user_role app_role;
begin
  -- Fetch the role of the user making the request
  select role into user_role 
  from public.user_roles 
  where user_id = auth.uid();

  -- Return true if the user's role matches or exceeds the level
  return user_role = requested_role;
end;
$$ language plpgsql security definer;